### ISSUE TITLE
Missing confidence interval of the current infected cases?

### ISSUE THREAD

**Issue by jbao** [Melykuti/COVID-19#1]
Cool, Bence, very interesting work again;-) I'm just wondering what does it mean that in the result table, some confidence intervals for the current infected cases (e.g. Germany) are missing?

**Comment by Melykuti** [comment]
Thanks. It was already explained in the text at the end of the Analysis section but now I refer back to it where I define the table columns.
Check out [the new German analysis](https://github.com/Melykuti/COVID-19/blob/master/Deutschland.md), it's very relevant to you.
